SELECT
  I.ANIMAL_ID,
  I.ANIMAL_TYPE,
  I.NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O
  ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE 1=1
  AND I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
  AND I.SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female')
ORDER BY I.ANIMAL_ID ASC
