SELECT  AI.ANIMAL_ID,
        AI.NAME
FROM ANIMAL_INS AI
                INNER JOIN ANIMAL_OUTS AO
                ON AI.ANIMAL_ID = AO.ANIMAL_ID
                AND AI.DATETIME > AO.DATETIME
WHERE 1=1
AND AO.DATETIME IS NOT NULL
ORDER BY AI.DATETIME ASC