SELECT
  I.ANIMAL_ID,
  I.NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O
  ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(
  SECOND,
  DATE_FORMAT(I.DATETIME, '%Y-%m-%d %H:%i:%s'),
  DATE_FORMAT(O.DATETIME, '%Y-%m-%d %H:%i:%s')) DESC
LIMIT 2
