SELECT  AO.ANIMAL_ID,
        AO.NAME
FROM ANIMAL_OUTS AO
                INNER JOIN ANIMAL_INS AI
                ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE 1=1
AND TIMESTAMPDIFF( MINUTE, DATE_FORMAT(AI.DATETIME, '%Y-%m-%d %H:%i'), DATE_FORMAT(AO.DATETIME, '%Y-%m-%d %H:%i:%s') )  > 0
ORDER BY TIMESTAMPDIFF( MINUTE, DATE_FORMAT(AI.DATETIME, '%Y-%m-%d %H:%i:%s'), DATE_FORMAT(AO.DATETIME, '%Y-%m-%d %H:%i:%s') ) DESC
LIMIT 2;